<?php
/***************************************************************************
 *  					Theme Functions
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 * 
 *  					Copyright (C) Themify
 * 						http://themify.me
 *
 *  To add custom PHP functions to the theme, create a new 'custom-functions.php' file in the theme folder.
 *  They will be added to the theme automatically.
 * 
 ***************************************************************************/

/////// Actions ////////
// Enqueue scripts and styles required by theme
add_action( 'wp_enqueue_scripts', 'themify_theme_enqueue_scripts', 11 );

// Browser compatibility
add_action( 'wp_head', 'themify_ie_enhancements' );
add_action( 'wp_head', 'themify_viewport_tag' );
add_action( 'wp_head', 'themify_ie_standards_compliant');

// Register custom menu
add_action( 'init', 'themify_register_custom_nav');

// Register sidebars
add_action( 'widgets_init', 'themify_theme_register_sidebars' );

// Add additional sidebar
add_action( 'themify_content_after', 'themify_theme_add_sidebar_alt' );
	
/////// Filters ////////

if ( ! function_exists( 'themify_theme_enqueue_scripts' ) ) {
	/**
	 * Enqueue Stylesheets and Scripts
	 * @since 1.0.0
	 */
	function themify_theme_enqueue_scripts(){

		// Get theme version for Themify theme scripts and styles
		$theme_version = wp_get_theme()->display('Version');

		///////////////////
		//Enqueue styles
		///////////////////

		// Themify base styling
		wp_enqueue_style( 'theme-style', get_stylesheet_uri(), array(), $theme_version);

		// Themify Media Queries CSS
		wp_enqueue_style( 'themify-media-queries', THEME_URI . '/media-queries.css', array(), $theme_version);

		//Google Web Fonts embedding
		wp_enqueue_style( 'google-fonts', themify_https_esc('http://fonts.googleapis.com/css'). '?family=Oswald|Open+Sans|Open+Sans:300&subset=latin,latin-ext');

		///////////////////
		//Enqueue scripts
		///////////////////

		// Nice scroll plugin
		// Load this desktop only
		$ua=$_SERVER['HTTP_USER_AGENT'];
		$browser = ((strpos($ua,'iPhone')!==false)||(strpos($ua,'iPod')!==false)||(strpos($ua,'iPad')!==false)||(strpos($ua,'Android')!==false));
		if ($browser == false){
			wp_enqueue_script( 'theme-scroll', THEME_URI . '/js/jquery.scroll.js', array('jquery'), $theme_version, true );
		}

		
		// Slide mobile navigation menu
		wp_enqueue_script( 'slide-nav', THEME_URI . '/js/jquery.sidr.min.js', array('jquery'), $theme_version, true );

		// Carousel (for breaking news)
		wp_enqueue_script( 'themify-carousel-js' );

		// Themify internal scripts
		wp_enqueue_script( 'theme-script',	THEME_URI . '/js/themify.script.js', array('jquery'), $theme_version, true );

		// Themify Gallery
		wp_enqueue_script( 'themify-gallery', THEMIFY_URI . '/js/themify.gallery.js', array('jquery'), false, true );

		// Inject variable values in gallery script
		wp_localize_script( 'theme-script', 'themifyScript', apply_filters('themify_script_vars',
			array(
				'lightbox' 		=> themify_lightbox_vars_init(),
				'lightboxContext' => apply_filters('themify_lightbox_context', '#pagewrap'),
				'fixedHeader' 	=> themify_check('setting-fixed_header_disabled')? '': 'fixed-header',
				'isTouch' => themify_is_touch()? 'true': 'false',
				'ajax_nonce'   	=> wp_create_nonce('ajax_nonce'),
				'ajax_url'	   	=> admin_url( 'admin-ajax.php' ),
				'events'		=> 'mouseenter',
				'top_nav_side'  => is_rtl() ? 'right' : 'left',
				'main_nav_side' => is_rtl() ? 'left' : 'right'
			)
		));

		// WordPress internal script to move the comment box to the right place when replying to a user
		if ( is_single() || is_page() ) wp_enqueue_script( 'comment-reply' );
	}
}

if ( ! function_exists( 'themify_ie_enhancements' ) ) {
	/**
 	 * Add JavaScript files if IE version is lower than 9
	 * @since 1.0.0
	 */
	function themify_ie_enhancements() {
		echo "\n".'
			<!-- media-queries.js -->
			<!--[if lt IE 9]>
				<script src="' . THEME_URI . '/js/respond.js"></script>
			<![endif]-->

			<!-- html5.js -->
			<!--[if lt IE 9]>
				<script src="'.themify_https_esc('http://html5shim.googlecode.com/svn/trunk/html5.js').'"></script>
			<![endif]-->
			'."\n";
	}
}

if ( ! function_exists( 'themify_viewport_tag' ) ) {
	/**
	 * Add viewport tag for responsive layouts
	 * @since 1.0.0
	 */
	function themify_viewport_tag(){
		echo "\n".'<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">'."\n";
	}
}

if ( ! function_exists( 'themify_ie_standards_compliant' ) ) {
	/**
	 * Make IE behave like a standards-compliant browser
	 * @since 1.0.0
	 */
	function themify_ie_standards_compliant() {
		echo "\n".'
		<!--[if lt IE 9]>
		<script src="'.themify_https_esc('http://s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js').'"></script>
		<script type="text/javascript" src="'.themify_https_esc('http://cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js').'"></script>
		<![endif]-->
		'."\n";
	}
}

/* Custom Write Panels
/***************************************************************************/

///////////////////////////////////////
// Build Write Panels
///////////////////////////////////////

// Include definitions for custom panels
foreach( array(	'post',	'page' ) as $cpt ) {
	// Load field definitions for custom post type
	require_once('admin/post-type-'.$cpt.'.php');
}
themify_build_write_panels( apply_filters('themify_theme_meta_boxes',
	array(
		array(
			'name'		=> __('Post Options', 'themify'), // Name displayed in box
			'id' => 'post-options',
			'options'	=> $post_meta_box, 	// Field options
			'pages'	=> 'post'					// Pages to show write panel
		),
		array(
			'name'		=> __('Page Options', 'themify'),
			'id' => 'page-options',
			'options'	=> $page_meta_box,
			'pages'	=> 'page'
		),
		array(
			"name"		=> __('Query Posts', 'themify'),
			'id' => 'query-posts',
			"options"	=> $query_post_meta_box,
			"pages"	=> "page"
		)
	)
));
	
	
/* Custom Functions
/***************************************************************************/	

///////////////////////////////////////
// Enable WordPress feature image
///////////////////////////////////////
add_theme_support( 'post-thumbnails' );
remove_post_type_support( 'page', 'thumbnail' );

if ( ! function_exists( 'themify_register_custom_nav' ) ) {
	/**
	 * Register Custom Menu Function
	 * @since 1.0.0
	 */
	function themify_register_custom_nav() {
		register_nav_menus( array(
			'top-nav' => __( 'Top Navigation', 'themify' ),
			'main-nav' => __( 'Main Navigation', 'themify' ),
			'footer-nav' => __( 'Footer Navigation', 'themify' ),
		));
	}
}

if ( ! function_exists( 'themify_default_main_nav' ) ) {
	/**
	 * Default Main Nav Function
	 * @since 1.0.0
	 */
	function themify_default_main_nav() {
		echo '<ul id="main-nav" class="main-nav clearfix">';
			wp_list_pages('title_li=');
		echo '</ul>';
	}
}

if ( ! function_exists( 'themify_theme_register_sidebars' ) ) {
	/**
	 * Register sidebars
	 * @since 1.0.0
	 */
	function themify_theme_register_sidebars() {
		$sidebars = array(
			array(
				'name' => __('Sidebar Wide', 'themify'),
				'id' => 'sidebar-main',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Sidebar Narrow', 'themify'),
				'id' => 'sidebar-alt',
				'before_widget' => '<div class="widgetwrap"><div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div></div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Sidebar Wide 2A', 'themify'),
				'id' => 'sidebar-main-2a',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Sidebar Wide 2B', 'themify'),
				'id' => 'sidebar-main-2b',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Sidebar Wide 3', 'themify'),
				'id' => 'sidebar-main-3',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Social Widget', 'themify'),
				'id' => 'social-widget',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<strong class="widgettitle">',
				'after_title' => '</strong>',
			),
			array(
				'name' => __('Header Widget', 'themify'),
				'id' => 'header-widget',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<strong class="widgettitle">',
				'after_title' => '</strong>',
			),
			array(
				'name' => __('Before Content Widget', 'themify'),
				'id' => 'before-content-widget',
				'before_widget' => '<div class="widgetwrap"><div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div></div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('After Content Widget', 'themify'),
				'id' => 'after-content-widget',
				'before_widget' => '<div class="widgetwrap"><div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div></div>',
				'before_title' => '<h4 class="widgettitle">',
				'after_title' => '</h4>',
			),
			array(
				'name' => __('Footer Social Widget', 'themify'),
				'id' => 'footer-social-widget',
				'before_widget' => '<div id="%1$s" class="widget %2$s">',
				'after_widget' => '</div>',
				'before_title' => '<strong class="widgettitle">',
				'after_title' => '</strong>',
			),
		);
		foreach( $sidebars as $sidebar ) {
			register_sidebar( $sidebar );
		}

		// Footer Sidebars
		themify_register_grouped_widgets();
	}
}

// Load Themify Mega Menu
require_once('theme-class-menu.php');

if( ! function_exists('themify_theme_add_sidebar_alt') ) {
	/**
	 * Includes narrow left sidebar
	 * @since 1.0.0
	 */
	function themify_theme_add_sidebar_alt() {
		global $themify;
		if( 'sidebar2' == $themify->layout || 'sidebar2 content-left' == $themify->layout || 'sidebar2 content-right' == $themify->layout ): ?>
			<!-- sidebar-narrow -->
			<?php get_template_part( 'includes/sidebar-alt'); ?>
			<!-- /sidebar-narrow -->
		<?php endif;
	}
}

if( ! function_exists('themify_theme_breaking_news') ) {
	/**
	 * Returns or echoes the breaking news list
	 * @param $term
	 * @param string $tag
	 * @param string $taxonomy
	 * @return mixed|void
	 * @since 1.0.0
	 */
	function themify_theme_breaking_news( $term, $tag = 'li', $taxonomy = 'category' ) {
		$tax_query = ($taxonomy == 'category' && $term == 'all-categories') ? '' : array(
			array(
				'taxonomy' => $taxonomy,
				'field' => 'slug',
				'terms' => $term
		));
		$posts = get_posts( array(
			'tax_query' => $tax_query,
			'suppress_filters' => false
		));
		$html = '';
		if( $posts ) {
			foreach($posts as $post) {
				$news = sprintf('<a href="%s" title="%s">%s</a>',
					get_permalink( $post->ID ),
					esc_attr(strip_tags(get_the_title( $post->ID ))),
					get_the_title( $post->ID )
				);
				if( '' != $tag ) {
					$html .= "<$tag>$news</$tag>";
				} else {
					$html .= $news;
				}
			}
		}
		return apply_filters('themify_theme_breaking_news', $html);
	}
}

if( ! function_exists('themify_theme_comment') ) {
	/**
	 * Custom Theme Comment
	 * @param object $comment Current comment.
	 * @param array $args Parameters for comment reply link.
	 * @param int $depth Maximum comment nesting depth.
	 * @since 1.0.0
	 */
	function themify_theme_comment($comment, $args, $depth) {
	   $GLOBALS['comment'] = $comment; ?>

		<li id="comment-<?php comment_ID() ?>" <?php comment_class(); ?>>
			<p class="comment-author">
				<?php printf('%s <cite>%s</cite>', get_avatar( $comment, $size='75' ), get_comment_author_link()); ?>
				<br />
				<small class="comment-time">
					<?php comment_date( apply_filters('themify_comment_date', 'M d, Y') ); ?>
					@
					<?php comment_time( apply_filters('themify_comment_time', 'H:i:s') ); ?>
					<?php edit_comment_link( __('Edit', 'themify'),' [',']'); ?>
				</small>
			</p>
			<div class="commententry">
				<?php if ($comment->comment_approved == '0') : ?>
					<p><em><?php _e('Your comment is awaiting moderation.', 'themify') ?></em></p>
				<?php endif; ?>
				<?php comment_text(); ?>
			</div>
			<p class="reply">
				<?php comment_reply_link(array_merge( $args, array('add_below' => 'comment', 'depth' => $depth, 'reply_text' => __( 'Reply', 'themify' ), 'max_depth' => $args['max_depth']))) ?>
			</p>
		<?php
	}
}

?>